-- Fraud Detection System - Database Schema

-- 1. Raw Transactions Table
CREATE TABLE IF NOT EXISTS raw_transactions (
    transaction_id VARCHAR(64) PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    time_step DOUBLE PRECISION NOT NULL,
    customer_id VARCHAR(64) NOT NULL,
    merchant_id VARCHAR(64) NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    v1 DOUBLE PRECISION,
    v2 DOUBLE PRECISION,
    v3 DOUBLE PRECISION,
    v4 DOUBLE PRECISION,
    v5 DOUBLE PRECISION,
    v6 DOUBLE PRECISION,
    v7 DOUBLE PRECISION,
    v8 DOUBLE PRECISION,
    v9 DOUBLE PRECISION,
    v10 DOUBLE PRECISION,
    v11 DOUBLE PRECISION,
    v12 DOUBLE PRECISION,
    v13 DOUBLE PRECISION,
    v14 DOUBLE PRECISION,
    v15 DOUBLE PRECISION,
    v16 DOUBLE PRECISION,
    v17 DOUBLE PRECISION,
    v18 DOUBLE PRECISION,
    v19 DOUBLE PRECISION,
    v20 DOUBLE PRECISION,
    v21 DOUBLE PRECISION,
    v22 DOUBLE PRECISION,
    v23 DOUBLE PRECISION,
    v24 DOUBLE PRECISION,
    v25 DOUBLE PRECISION,
    v26 DOUBLE PRECISION,
    v27 DOUBLE PRECISION,
    v28 DOUBLE PRECISION,
    is_fraud INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_raw_tx_cust_time ON raw_transactions (customer_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_raw_tx_merchant ON raw_transactions (merchant_id);

-- 2. Engineered Features Table
CREATE TABLE IF NOT EXISTS engineered_features (
    transaction_id VARCHAR(64) PRIMARY KEY REFERENCES raw_transactions(transaction_id) ON DELETE CASCADE,
    customer_id VARCHAR(64) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    velocity_5m INTEGER NOT NULL DEFAULT 0,
    velocity_60m INTEGER NOT NULL DEFAULT 0,
    amount_deviation DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    time_since_last_tx_sec DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    geo_distance_km DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    v1 DOUBLE PRECISION,
    v2 DOUBLE PRECISION,
    v3 DOUBLE PRECISION,
    v4 DOUBLE PRECISION,
    v5 DOUBLE PRECISION,
    v6 DOUBLE PRECISION,
    v7 DOUBLE PRECISION,
    v8 DOUBLE PRECISION,
    v9 DOUBLE PRECISION,
    v10 DOUBLE PRECISION,
    v11 DOUBLE PRECISION,
    v12 DOUBLE PRECISION,
    v13 DOUBLE PRECISION,
    v14 DOUBLE PRECISION,
    v15 DOUBLE PRECISION,
    v16 DOUBLE PRECISION,
    v17 DOUBLE PRECISION,
    v18 DOUBLE PRECISION,
    v19 DOUBLE PRECISION,
    v20 DOUBLE PRECISION,
    v21 DOUBLE PRECISION,
    v22 DOUBLE PRECISION,
    v23 DOUBLE PRECISION,
    v24 DOUBLE PRECISION,
    v25 DOUBLE PRECISION,
    v26 DOUBLE PRECISION,
    v27 DOUBLE PRECISION,
    v28 DOUBLE PRECISION,
    is_fraud INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_eng_features_cust ON engineered_features (customer_id);

-- 3. Audit Log Table (Model Risk Management & Decision Reconstruction)
CREATE TABLE IF NOT EXISTS audit_log (
    audit_id SERIAL PRIMARY KEY,
    transaction_id VARCHAR(64) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    input_hash VARCHAR(64) NOT NULL,
    model_version VARCHAR(64) NOT NULL,
    fraud_score DOUBLE PRECISION NOT NULL,
    is_flagged BOOLEAN NOT NULL,
    agent_decision VARCHAR(32), -- 'APPROVE', 'ESCALATE', 'DECLINE'
    agent_report JSONB,
    guardrail_status VARCHAR(32), -- 'PASSED', 'NEEDS_REVIEW', 'SKIPPED'
    faithfulness_score DOUBLE PRECISION,
    latency_ms DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_log_tx ON audit_log (transaction_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON audit_log (timestamp DESC);
